# Generated by Django 5.1.5 on 2025-01-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transactionid', models.AutoField(primary_key=True, serialize=False)),
                ('transactiondate', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('repaid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('card', models.CharField(max_length=50)),
            ],
        ),
    ]
