# Generated by Django 5.1.5 on 2025-01-25 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transactions',
            table='transactions',
        ),
    ]
