# Generated by Django 5.1.7 on 2025-04-01 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_account_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('atid', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='atype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.accounttype'),
        ),
    ]
