# Generated by Django 5.1.5 on 2025-02-04 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_account_category_debt_payment_pointrule_transaction_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debt',
            old_name='borrowerName',
            new_name='borrowername',
        ),
        migrations.RenameField(
            model_name='debt',
            old_name='transaction',
            new_name='tid',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='aidFrom',
            new_name='aidfrom',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='aidTo',
            new_name='aidto',
        ),
        migrations.RenameField(
            model_name='pointrule',
            old_name='pointsPerDollar',
            new_name='pointsperdollar',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='isShared',
            new_name='isshared',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='pointsEarned',
            new_name='pointsearned',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(db_column='aid', on_delete=django.db.models.deletion.CASCADE, to='api.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(db_column='cid', on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
        migrations.AlterUniqueTogether(
            name='debt',
            unique_together={('tid', 'borrowername')},
        ),
    ]
