# Generated by Django 5.1.7 on 2025-04-01 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_accounttype_alter_account_atype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounttype',
            old_name='atid',
            new_name='atype_id',
        ),
    ]
