# Generated by Django 5.1.7 on 2025-04-01 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_atid_accounttype_atype_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryType',
            fields=[
                ('ctype_id', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=75)),
            ],
        ),
        migrations.RenameField(
            model_name='account',
            old_name='atype',
            new_name='atype_id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='ctype',
        ),
        migrations.AddField(
            model_name='transaction',
            name='points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='category',
            name='ctype_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.categorytype'),
        ),
        migrations.CreateModel(
            name='PointRules',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('multiplier', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
            options={
                'unique_together': {('aid', 'cid')},
            },
        ),
    ]
