# Generated by Django 5.1.7 on 2025-04-01 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_categorytype_rename_atype_account_atype_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounttype',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='categorytype',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='desc',
            new_name='description',
        ),
    ]
