name: Deploy Portfolio to GitHub Pages

# Trigger on pushes to your default branch
on:
  push:
    branches:
      - main

jobs:
  pages:
    # Use the special pages environment so GitHub knows this is a Pages deployment
    environment:
      name: github-pages
      # This makes GitHub display the URL in Actions UI
      url: https://stixvish.github.io
    runs-on: ubuntu-latest

    steps:
      # 1. Get your source code
      - name: Checkout source
        uses: actions/checkout@v4

      # 2. Set up Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 3. Install & build
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build

      # 4. Configure the Pages environment
      - name: Configure Pages
        uses: actions/configure-pages@v3

      # 5. Upload the build output (dist/) as the Pages artifact
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./dist

      # 6. Deploy to GitHub Pages
      - name: Deploy to Pages
        uses: actions/deploy-pages@v2
